spring.application.name=galeria-seleta-api
server.port=8080

logging.level.com.galeriaseleta=DEBUG

# Futuramente: configurações do banco de dados SQLite
# spring.datasource.url=jdbc:sqlite:galeriaseleta.db
# spring.datasource.driver-class-name=org.sqlite.JDBC
# spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Futuramente: configurações de JWT
# jwt.secret=sua-chave-secreta
# jwt.expiration=86400000
